# Generated by Django 5.2.7 on 2025-11-30 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendaftaranAK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('ttl', models.CharField(max_length=255)),
                ('jk', models.CharField(choices=[('LAKI-LAKI', 'Laki-Laki'), ('PEREMPUAN', 'Perempuan')], max_length=10)),
                ('status_perkawinan', models.CharField(choices=[('BELUM KAWIN', 'Belum Kawin'), ('KAWIN', 'Kawin'), ('CERAI HIDUP', 'Cerai Hidup'), ('CERAI MATI', 'Cerai Mati')], max_length=15)),
                ('pendidikan', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.TextField()),
                ('keahlian', models.CharField(blank=True, max_length=255, null=True)),
                ('pengalaman', models.TextField(blank=True, null=True)),
                ('photo_data', models.TextField(blank=True, null=True)),
                ('ijazah_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('diverifikasi', 'Diverifikasi'), ('ditolak', 'Ditolak')], default='pending', max_length=15)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
