# Generated by Django 5.2.7 on 2025-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaranak1',
            name='ktp_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
